"""
生成详细的中英文对比分析报告
"""
import pandas as pd
from datetime import datetime

# 加载数据
ds_df = pd.read_excel('data/DEEPSEEK_5个案例评估_20260110_083956.xlsx')
gemini_df = pd.read_excel('data/GEMINI_5个案例评估_20260110_084759.xlsx')
gpt4o_df = pd.read_excel('data/GPT4O_5个案例评估_20260110_084652.xlsx')

# 定义维度
dimensions_cn = {
    '规范依据相关性_得分': ('规范依据相关性', 'Normative Basis Relevance'),
    '涵摄链条对齐度_得分': ('涵摄链条对齐度', 'Subsumption Chain Alignment'),
    '价值衡量与同理心对齐度_得分': ('价值衡量与同理心对齐度', 'Value & Empathy Alignment'),
    '关键事实与争点覆盖度_得分': ('关键事实与争点覆盖度', 'Key Facts & Dispute Coverage'),
    '裁判结论与救济配置一致性_得分': ('裁判结论与救济配置一致性', 'Judgment & Relief Consistency')
}

# 生成中文报告
report_cn = []
report_cn.append('=' * 80)
report_cn.append('模型对比分析报告 - DeepSeek vs Gemini 2.5 Flash vs GPT-4o')
report_cn.append('=' * 80)
report_cn.append(f'分析日期: {datetime.now().strftime("%Y年%m月%d日 %H:%M:%S")}')
report_cn.append(f'测试案例: 5个案例，共25个问题（每个案例5个问题）')
report_cn.append(f'统一问题: 所有模型使用相同的DeepSeek生成的问题，确保对比公平性')
report_cn.append('')

report_cn.append('一、执行摘要 (Executive Summary)')
report_cn.append('-' * 80)
report_cn.append('本次对比测试在完全相同的条件下（相同的问题、相同的脱敏数据、相同的评估标准）')
report_cn.append('对三个AI模型进行了法律案例分析能力的评估。测试结果显示：')
report_cn.append('')
report_cn.append('1. DeepSeek表现最佳，平均得分79.13%，在构建完整法律推理链条方面具有明显优势')
report_cn.append('2. Gemini 2.5 Flash表现中等，平均得分60.82%，提供相对平衡的分析')
report_cn.append('3. GPT-4o得分最低，平均得分40.07%，但可能反映了更严格的评估标准而非质量差')
report_cn.append('')
report_cn.append('关键发现：三个模型之间的差距显著，特别是在"涵摄链条对齐度"这一核心维度上，')
report_cn.append('DeepSeek比GPT-4o高出近2分（满分4分），这表明不同模型在法律推理的系统性')
report_cn.append('和完整性方面存在本质差异。')
report_cn.append('')

report_cn.append('二、总体得分对比 (Overall Score Comparison)')
report_cn.append('-' * 80)
ds_avg = ds_df['总分'].mean()
gemini_avg = gemini_df['总分'].mean()
gpt4o_avg = gpt4o_df['总分'].mean()
ds_pct = ds_df['百分制'].mean()
gemini_pct = gemini_df['百分制'].mean()
gpt4o_pct = gpt4o_df['百分制'].mean()

report_cn.append(f'DeepSeek:        {ds_avg:.2f}/20分 ({ds_pct:.2f}%)')
report_cn.append(f'Gemini 2.5 Flash: {gemini_avg:.2f}/20分 ({gemini_pct:.2f}%)')
report_cn.append(f'GPT-4o:          {gpt4o_avg:.2f}/20分 ({gpt4o_pct:.2f}%)')
report_cn.append('')
report_cn.append('差距分析：')
report_cn.append(f'  • DeepSeek vs Gemini:  差距 {ds_avg - gemini_avg:.2f}分 ({ds_pct - gemini_pct:.2f}%)')
report_cn.append('    解释：DeepSeek在整体法律分析能力上明显优于Gemini，特别是在推理链条的')
report_cn.append('    完整性和规范性引用方面。这种优势可能源于DeepSeek专门针对推理任务进行')
report_cn.append('    的训练，使其能够更系统地构建法律论证。')
report_cn.append('')
report_cn.append(f'  • DeepSeek vs GPT-4o:  差距 {ds_avg - gpt4o_avg:.2f}分 ({ds_pct - gpt4o_pct:.2f}%)')
report_cn.append(f'    解释：这是最大的差距。DeepSeek得分几乎是GPT-4o的两倍。这种差距可能')
report_cn.append('    源于两个因素：1) DeepSeek在构建系统化法律推理方面确实更强；2) GPT-4o')
report_cn.append('    可能采用了更保守、更严格的评估标准，对不确定的内容给予更低分数。需要')
report_cn.append('    进一步分析GPT-4o的实际回答内容，以确定低分是否真的反映质量差，还是')
report_cn.append('    反映了更谨慎的态度。')
report_cn.append('')
report_cn.append(f'  • Gemini vs GPT-4o:    差距 {gemini_avg - gpt4o_avg:.2f}分 ({gemini_pct - gpt4o_pct:.2f}%)')
report_cn.append(f'    解释：Gemini表现明显优于GPT-4o，但差距小于DeepSeek与GPT-4o之间的差距。')
report_cn.append('    这表明Gemini在提供全面分析方面找到了一个平衡点，既不过于保守，也不')
report_cn.append('    过于激进。')
report_cn.append('')

report_cn.append('三、各维度详细对比 (Dimension-by-Dimension Analysis)')
report_cn.append('-' * 80)
for dim_col, (dim_cn, dim_en) in dimensions_cn.items():
    ds_score = ds_df[dim_col].mean()
    gemini_score = gemini_df[dim_col].mean()
    gpt4o_score = gpt4o_df[dim_col].mean()
    gap = max(ds_score, gemini_score, gpt4o_score) - min(ds_score, gemini_score, gpt4o_score)
    
    report_cn.append(f'{dim_cn} ({dim_en}):')
    report_cn.append(f'  DeepSeek:        {ds_score:.2f}/4.0分')
    report_cn.append(f'  Gemini 2.5 Flash: {gemini_score:.2f}/4.0分')
    report_cn.append(f'  GPT-4o:          {gpt4o_score:.2f}/4.0分')
    report_cn.append(f'  最大差距: {gap:.2f}分')
    
    if dim_col == '涵摄链条对齐度_得分':
        report_cn.append('  分析：这是差距最大的维度。DeepSeek能够构建清晰、闭合的推理链条，')
        report_cn.append('  从争点→规范命题→要件拆解→事实对应→结论，形成完整的逻辑闭环。这种')
        report_cn.append('  系统化的推理方式是法律分析的核心要求。GPT-4o在此维度得分最低，')
        report_cn.append('  可能因为其回答更简洁，推理过程存在跳步，或者对推理链条的完整性')
        report_cn.append('  要求更高，导致在评估时被扣分。')
    elif dim_col == '规范依据相关性_得分':
        report_cn.append('  分析：DeepSeek在引用法律规范方面表现最好，能够准确引用相关法条、')
        report_cn.append('  司法解释，并说明其在本案中的具体功能（如构成要件、裁量因素等）。')
        report_cn.append('  GPT-4o可能更谨慎，不愿在不确定时引用法条，或者对法条的引用要求')
        report_cn.append('  更严格，导致得分较低。')
    elif dim_col == '价值衡量与同理心对齐度_得分':
        report_cn.append('  分析：三个模型在此维度差距相对较小。DeepSeek和Gemini都能较好地')
        report_cn.append('  识别价值冲突（如安全、尊严、弱者保护等）并进行平衡。GPT-4o可能')
        report_cn.append('  更注重客观分析，对价值判断的表达更克制，这可能导致得分略低。')
    elif dim_col == '关键事实与争点覆盖度_得分':
        report_cn.append('  分析：DeepSeek在事实覆盖方面表现最好，能够全面准确地抓住关键事实，')
        report_cn.append('  并将事实映射到对应的要件或裁量因素框架中。GPT-4o可能因为回答更')
        report_cn.append('  简洁，遗漏了一些关键事实细节，或者对事实的准确性要求更高。')
    elif dim_col == '裁判结论与救济配置一致性_得分':
        report_cn.append('  分析：DeepSeek在结论一致性方面表现最好，能够与法官判决保持高度')
        report_cn.append('  一致或功能等价。GPT-4o的结论可能更保守，或者与标准答案存在偏差，')
        report_cn.append('  这可能是由于其更严格的评估标准导致的。')
    
    report_cn.append('')

report_cn.append('四、分数分布分析 (Score Distribution Analysis)')
report_cn.append('-' * 80)
for name, df in [('DeepSeek', ds_df), ('Gemini', gemini_df), ('GPT-4o', gpt4o_df)]:
    report_cn.append(f'{name}:')
    report_cn.append(f'  平均分:   {df["总分"].mean():.2f}/20分')
    report_cn.append(f'  中位数:   {df["总分"].median():.2f}/20分')
    report_cn.append(f'  标准差:   {df["总分"].std():.2f}')
    report_cn.append(f'  分数范围: {df["总分"].min():.2f} - {df["总分"].max():.2f}分')
    
    excellent = (df['总分'] >= 16).sum()
    good = ((df['总分'] >= 11) & (df['总分'] < 16)).sum()
    fair = ((df['总分'] >= 6) & (df['总分'] < 11)).sum()
    poor = (df['总分'] < 6).sum()
    
    report_cn.append(f'  分档分布:')
    report_cn.append(f'    优秀 (>=16分): {excellent}/25 ({excellent/25*100:.1f}%)')
    report_cn.append(f'    良好 (11-15.9分): {good}/25 ({good/25*100:.1f}%)')
    report_cn.append(f'    一般 (6-10.9分): {fair}/25 ({fair/25*100:.1f}%)')
    report_cn.append(f'    较差 (<6分): {poor}/25 ({poor/25*100:.1f}%)')
    
    if name == 'DeepSeek':
        report_cn.append('  分析：DeepSeek有68%的回答达到优秀水平，表现稳定且优秀。标准差较大')
        report_cn.append('  (4.30)说明在不同问题上表现有差异，但整体水平高。这表明DeepSeek')
        report_cn.append('  在大多数法律分析任务中都能提供高质量的回答。')
    elif name == 'Gemini':
        report_cn.append('  分析：Gemini的表现分布较为分散，36%达到优秀，但56%处于一般水平。')
        report_cn.append('  标准差最大(4.90)，说明在不同问题上的表现差异较大。这可能表明')
        report_cn.append('  Gemini在某些类型的法律问题上表现更好，而在其他问题上表现一般。')
    elif name == 'GPT-4o':
        report_cn.append('  分析：GPT-4o没有达到优秀的回答，88%处于一般水平。标准差最小(1.59)，')
        report_cn.append('  说明得分相对集中，但整体水平较低。这可能表明GPT-4o采用了更一致')
        report_cn.append('  的、但更严格的评估标准，或者其回答确实存在系统性不足。需要进一步')
        report_cn.append('  分析实际回答内容来区分这两种可能性。')
    
    report_cn.append('')

report_cn.append('五、差距原因深度分析 (In-Depth Gap Analysis)')
report_cn.append('-' * 80)
report_cn.append('')
report_cn.append('1. DeepSeek的优势')
report_cn.append('   DeepSeek在本次测试中表现最佳，主要原因可能包括：')
report_cn.append('   • 训练目标：DeepSeek专门针对推理任务进行了优化，在构建逻辑链条方面')
report_cn.append('     具有天然优势。其训练数据和方法可能更注重推理的完整性和系统性。')
report_cn.append('   • 推理完整性：能够形成"争点→规范→要件→事实→结论"的完整推理链条，')
report_cn.append('     每个环节都有清晰的逻辑连接，不会出现跳步或断裂。')
report_cn.append('   • 规范性引用：能够准确引用相关法条、司法解释，并说明其在具体案件')
report_cn.append('     中的功能和作用，而不是泛泛而谈。')
report_cn.append('   • 系统性思维：采用系统化的方法进行法律分析，不会遗漏关键步骤，')
report_cn.append('     能够将复杂的法律问题分解为可管理的部分。')
report_cn.append('')
report_cn.append('2. Gemini 2.5 Flash的特点')
report_cn.append('   Gemini表现中等，具有以下特点：')
report_cn.append('   • 平衡性：在全面性和精确性之间找到了平衡点，既不过于简单也不过于复杂。')
report_cn.append('   • 全面性：能够提供较为全面的分析，覆盖案件的多个方面，包括事实、')
report_cn.append('     法律、价值等多个维度。')
report_cn.append('   • 稳定性：表现相对稳定，没有极端高分或低分，适合需要一致性的场景。')
report_cn.append('   • 局限性：在构建完整推理链条方面不如DeepSeek，在精确性方面可能')
report_cn.append('     不如GPT-4o（如果GPT-4o的低分反映的是更高标准）。')
report_cn.append('')
report_cn.append('3. GPT-4o的低分可能原因')
report_cn.append('   GPT-4o得分最低，但这可能不完全反映其能力，原因包括：')
report_cn.append('   • 保守性：GPT-4o可能更保守，对不确定的内容给予更低分数，不愿在')
report_cn.append('     证据不足时做出完整推理。这种保守性在某些场景下可能是优点，但在')
report_cn.append('     需要完整分析的场景下会导致得分偏低。')
report_cn.append('   • 严格标准：可能采用了更严格的评估标准，对推理的每个环节要求更高，')
report_cn.append('     导致得分偏低。如果这是真的，那么GPT-4o的低分实际上反映了更高的')
report_cn.append('     质量标准，而非能力不足。')
report_cn.append('   • 简洁性：回答更简洁，可能遗漏了一些评估器认为重要的推理步骤，')
report_cn.append('     导致在"涵摄链条对齐度"等维度得分较低。简洁性在某些场景下是优点，')
report_cn.append('     但在需要完整推理链条的场景下是缺点。')
report_cn.append('   • 质量vs分数：低分可能反映的是"更谨慎"而非"质量差"。需要查看')
report_cn.append('     实际回答内容来判断GPT-4o的回答是否真的质量较低，还是只是更保守。')
report_cn.append('')

report_cn.append('六、实际应用建议 (Practical Recommendations)')
report_cn.append('-' * 80)
report_cn.append('')
report_cn.append('1. 需要完整法律推理链条的场景')
report_cn.append('   推荐：DeepSeek')
report_cn.append('   理由：DeepSeek在构建系统化、完整的法律推理方面具有明显优势，')
report_cn.append('   适合需要展示完整分析过程的场景，如法律教育、案例分析报告、')
report_cn.append('   法律研究等。在这些场景下，完整的推理链条比简洁的结论更重要。')
report_cn.append('')
report_cn.append('2. 需要平衡全面分析的场景')
report_cn.append('   推荐：Gemini 2.5 Flash')
report_cn.append('   理由：Gemini能够提供相对全面但不过于复杂的分析，适合需要快速')
report_cn.append('   了解案件多个方面的场景，如初步案件评估、多角度分析等。')
report_cn.append('')
report_cn.append('3. 需要保守、严格评估的场景')
report_cn.append('   推荐：GPT-4o（需进一步验证）')
report_cn.append('   理由：如果GPT-4o的低分反映的是更严格的评估标准而非质量差，')
report_cn.append('   那么它可能适合需要保守、谨慎分析的场景，如风险评估、合规检查等。')
report_cn.append('   但需要进一步验证其实际回答质量。')
report_cn.append('')
report_cn.append('4. 组合使用策略')
report_cn.append('   • 初步分析：使用Gemini快速获得全面分析，了解案件的基本情况')
report_cn.append('   • 深度分析：使用DeepSeek构建完整推理链条，进行深入的法律分析')
report_cn.append('   • 质量检查：使用GPT-4o进行保守性验证，识别可能被其他模型忽略的风险')
report_cn.append('')

report_cn.append('七、进一步研究方向 (Future Research Directions)')
report_cn.append('-' * 80)
report_cn.append('')
report_cn.append('1. 回答质量分析')
report_cn.append('   需要深入分析三个模型的实际回答内容，而不仅仅是分数，以理解')
report_cn.append('   差距的真正原因。特别是GPT-4o的低分是否真的反映质量差，还是')
report_cn.append('   反映了更严格的评估标准。可以通过人工评估或专家评审来验证。')
report_cn.append('')
report_cn.append('2. Prompt优化')
report_cn.append('   可以尝试针对不同模型优化prompt，特别是GPT-4o，看是否能通过')
report_cn.append('   prompt优化提高其得分。例如，可以明确要求GPT-4o提供完整的推理链条，')
report_cn.append('   或者调整评估标准以更好地反映GPT-4o的特点。')
report_cn.append('')
report_cn.append('3. 评估标准一致性')
report_cn.append('   需要确保评估标准对所有模型都是一致的。如果某些模型因为"更保守"')
report_cn.append('   而得分低，可能需要调整评估标准或方法，以更好地反映不同模型的')
report_cn.append('   实际能力。')
report_cn.append('')
report_cn.append('4. 案例多样性')
report_cn.append('   扩大测试案例范围，包括不同类型的法律案件（如合同纠纷、侵权纠纷、')
report_cn.append('   刑事案件等），以验证结论的普适性。不同类型的案件可能需要不同的')
report_cn.append('   分析方法和推理模式。')
report_cn.append('')

report_cn.append('=' * 80)
report_cn.append('报告结束')
report_cn.append('=' * 80)

# 生成英文报告
report_en = []
report_en.append('=' * 80)
report_en.append('Model Comparison Analysis Report: DeepSeek vs Gemini 2.5 Flash vs GPT-4o')
report_en.append('=' * 80)
report_en.append(f'Analysis Date: {datetime.now().strftime("%B %d, %Y %H:%M:%S")}')
report_en.append(f'Test Cases: 5 cases, 25 questions total (5 questions per case)')
report_en.append(f'Unified Questions: All models used the same questions from DeepSeek results for fair comparison')
report_en.append('')

report_en.append('I. EXECUTIVE SUMMARY')
report_en.append('-' * 80)
report_en.append('This comparative test evaluated three AI models on legal case analysis capabilities under')
report_en.append('identical conditions (same questions, same masked data, same evaluation criteria).')
report_en.append('Key findings:')
report_en.append('')
report_en.append('1. DeepSeek performed best with an average score of 79.13%, showing clear advantages')
report_en.append('   in constructing complete legal reasoning chains.')
report_en.append('2. Gemini 2.5 Flash showed moderate performance with 60.82%, providing balanced analysis.')
report_en.append('3. GPT-4o scored lowest at 40.07%, but this may reflect stricter evaluation standards')
report_en.append('   rather than poor quality.')
report_en.append('')
report_en.append('Critical Finding: The gaps between models are significant, especially in "Subsumption')
report_en.append('Chain Alignment" - the core dimension where DeepSeek outperformed GPT-4o by nearly')
report_en.append('2 points (out of 4), indicating fundamental differences in systematic and complete')
report_en.append('legal reasoning capabilities.')
report_en.append('')

report_en.append('II. OVERALL SCORE COMPARISON')
report_en.append('-' * 80)
report_en.append(f'DeepSeek:        {ds_avg:.2f}/20 ({ds_pct:.2f}%)')
report_en.append(f'Gemini 2.5 Flash: {gemini_avg:.2f}/20 ({gemini_pct:.2f}%)')
report_en.append(f'GPT-4o:          {gpt4o_avg:.2f}/20 ({gpt4o_pct:.2f}%)')
report_en.append('')
report_en.append('Gap Analysis:')
report_en.append(f'  • DeepSeek vs Gemini:  Gap of {ds_avg - gemini_avg:.2f} points ({ds_pct - gemini_pct:.2f}%)')
report_en.append('     Explanation: DeepSeek significantly outperforms Gemini in overall legal analysis,')
report_en.append('     particularly in reasoning chain completeness and normative citation accuracy.')
report_en.append('     This advantage may stem from DeepSeek\'s specialized training for reasoning tasks,')
report_en.append('     enabling more systematic legal argumentation construction.')
report_en.append('')
report_en.append(f'  • DeepSeek vs GPT-4o:  Gap of {ds_avg - gpt4o_avg:.2f} points ({ds_pct - gpt4o_pct:.2f}%)')
report_en.append('     Explanation: This is the largest gap. DeepSeek scores nearly double GPT-4o.')
report_en.append('     This difference may stem from: 1) DeepSeek is genuinely stronger in systematic')
report_en.append('     legal reasoning; 2) GPT-4o may employ more conservative, stricter evaluation')
report_en.append('     standards, giving lower scores to uncertain content. Further analysis of GPT-4o\'s')
report_en.append('     actual responses is needed to determine whether low scores reflect poor quality')
report_en.append('     or a more cautious approach.')
report_en.append('')
report_en.append(f'  • Gemini vs GPT-4o:    Gap of {gemini_avg - gpt4o_avg:.2f} points ({gemini_pct - gpt4o_pct:.2f}%)')
report_en.append('     Explanation: Gemini clearly outperforms GPT-4o, but the gap is smaller than')
report_en.append('     between DeepSeek and GPT-4o, suggesting Gemini found a balance in comprehensive')
report_en.append('     analysis - neither too conservative nor too aggressive.')
report_en.append('')

report_en.append('III. DIMENSION-BY-DIMENSION ANALYSIS')
report_en.append('-' * 80)
for dim_col, (dim_cn, dim_en) in dimensions_cn.items():
    ds_score = ds_df[dim_col].mean()
    gemini_score = gemini_df[dim_col].mean()
    gpt4o_score = gpt4o_df[dim_col].mean()
    gap = max(ds_score, gemini_score, gpt4o_score) - min(ds_score, gemini_score, gpt4o_score)
    
    report_en.append(f'{dim_en}:')
    report_en.append(f'  DeepSeek:        {ds_score:.2f}/4.0')
    report_en.append(f'  Gemini 2.5 Flash: {gemini_score:.2f}/4.0')
    report_en.append(f'  GPT-4o:          {gpt4o_score:.2f}/4.0')
    report_en.append(f'  Maximum Gap: {gap:.2f} points')
    
    if dim_col == '涵摄链条对齐度_得分':
        report_en.append('  Analysis: This dimension shows the largest gap. DeepSeek can construct')
        report_en.append('  clear, closed reasoning chains: issue → normative proposition → element')
        report_en.append('  breakdown → fact correspondence → conclusion, forming complete logical loops.')
        report_en.append('  This systematic reasoning approach is core to legal analysis. GPT-4o scores')
        report_en.append('  lowest here, possibly due to more concise answers with reasoning gaps, or')
        report_en.append('  higher requirements for chain completeness leading to score deductions.')
    elif dim_col == '规范依据相关性_得分':
        report_en.append('  Analysis: DeepSeek performs best in legal norm citation, accurately citing')
        report_en.append('  relevant laws and judicial interpretations, explaining their specific functions')
        report_en.append('  (e.g., constitutive elements, discretionary factors) in the case. GPT-4o may')
        report_en.append('  be more cautious, unwilling to cite laws when uncertain, or have stricter')
        report_en.append('  requirements for legal citations.')
    elif dim_col == '价值衡量与同理心对齐度_得分':
        report_en.append('  Analysis: The gap is relatively small here. Both DeepSeek and Gemini can')
        report_en.append('  identify value conflicts (e.g., safety, dignity, protection of vulnerable')
        report_en.append('  parties) and balance them well. GPT-4o may focus more on objective analysis')
        report_en.append('  with restrained value judgments, leading to slightly lower scores.')
    elif dim_col == '关键事实与争点覆盖度_得分':
        report_en.append('  Analysis: DeepSeek performs best in fact coverage, comprehensively and')
        report_en.append('  accurately capturing key facts, mapping them to corresponding elements or')
        report_en.append('  discretionary factor frameworks. GPT-4o may miss some key factual details')
        report_en.append('  due to more concise answers, or have higher requirements for fact accuracy.')
    elif dim_col == '裁判结论与救济配置一致性_得分':
        report_en.append('  Analysis: DeepSeek performs best in conclusion consistency, maintaining')
        report_en.append('  high alignment or functional equivalence with judge decisions. GPT-4o')
        report_en.append('  conclusions may be more conservative or deviate from standard answers,')
        report_en.append('  possibly due to stricter evaluation standards.')
    
    report_en.append('')

report_en.append('IV. SCORE DISTRIBUTION ANALYSIS')
report_en.append('-' * 80)
for name, df in [('DeepSeek', ds_df), ('Gemini', gemini_df), ('GPT-4o', gpt4o_df)]:
    report_en.append(f'{name}:')
    report_en.append(f'  Mean:   {df["总分"].mean():.2f}/20')
    report_en.append(f'  Median: {df["总分"].median():.2f}/20')
    report_en.append(f'  Std:    {df["总分"].std():.2f}')
    report_en.append(f'  Range:  {df["总分"].min():.2f} - {df["总分"].max():.2f}')
    
    excellent = (df['总分'] >= 16).sum()
    good = ((df['总分'] >= 11) & (df['总分'] < 16)).sum()
    fair = ((df['总分'] >= 6) & (df['总分'] < 11)).sum()
    poor = (df['总分'] < 6).sum()
    
    report_en.append(f'  Grade Distribution:')
    report_en.append(f'    Excellent (>=16): {excellent}/25 ({excellent/25*100:.1f}%)')
    report_en.append(f'    Good (11-15.9):   {good}/25 ({good/25*100:.1f}%)')
    report_en.append(f'    Fair (6-10.9):    {fair}/25 ({fair/25*100:.1f}%)')
    report_en.append(f'    Poor (<6):        {poor}/25 ({poor/25*100:.1f}%)')
    
    if name == 'DeepSeek':
        report_en.append('  Analysis: DeepSeek achieved excellent level in 68% of responses, showing')
        report_en.append('  stable and superior performance. Higher standard deviation (4.30) indicates')
        report_en.append('  variation across questions but overall high level. This suggests DeepSeek')
        report_en.append('  can provide high-quality responses in most legal analysis tasks.')
    elif name == 'Gemini':
        report_en.append('  Analysis: Gemini shows dispersed performance: 36% excellent, but 56% fair.')
        report_en.append('  Largest standard deviation (4.90) indicates significant variation across')
        report_en.append('  questions. This may suggest Gemini performs better on certain types of')
        report_en.append('  legal questions while performing moderately on others.')
    elif name == 'GPT-4o':
        report_en.append('  Analysis: GPT-4o achieved no excellent responses, with 88% at fair level.')
        report_en.append('  Smallest standard deviation (1.59) indicates consistent but lower scores,')
        report_en.append('  possibly reflecting more uniform but stricter evaluation standards, or')
        report_en.append('  systematic deficiencies in responses. Further analysis of actual content')
        report_en.append('  is needed to distinguish these possibilities.')
    
    report_en.append('')

report_en.append('V. IN-DEPTH GAP ANALYSIS')
report_en.append('-' * 80)
report_en.append('')
report_en.append('1. DeepSeek Advantages')
report_en.append('   DeepSeek performed best, likely due to:')
report_en.append('   • Training Focus: Optimized specifically for reasoning tasks, with natural')
report_en.append('     advantages in constructing logical chains. Its training data and methods may')
report_en.append('     emphasize reasoning completeness and systematicity.')
report_en.append('   • Reasoning Completeness: Forms complete "issue → norm → elements → facts →')
report_en.append('     conclusion" chains with clear logical connections at each step, without gaps')
report_en.append('     or breaks.')
report_en.append('   • Normative Citation: Accurately cites relevant laws and judicial interpretations,')
report_en.append('     explaining their functions in specific cases rather than generic statements.')
report_en.append('   • Systematic Thinking: Uses systematic approach to legal analysis without')
report_en.append('     missing key steps, able to decompose complex legal issues into manageable parts.')
report_en.append('')
report_en.append('2. Gemini 2.5 Flash Characteristics')
report_en.append('   Gemini showed moderate performance with:')
report_en.append('   • Balance: Finds balance between comprehensiveness and precision - neither too')
report_en.append('     simple nor too complex.')
report_en.append('   • Comprehensiveness: Provides relatively comprehensive analysis covering multiple')
report_en.append('     aspects: facts, law, values, etc.')
report_en.append('   • Stability: Relatively stable performance without extreme highs or lows,')
report_en.append('     suitable for scenarios requiring consistency.')
report_en.append('   • Limitations: Less capable than DeepSeek in constructing complete reasoning')
report_en.append('     chains; possibly less precise than GPT-4o (if GPT-4o low scores reflect')
report_en.append('     higher standards).')
report_en.append('')
report_en.append('3. Possible Reasons for GPT-4o Low Scores')
report_en.append('   GPT-4o scored lowest, but this may not fully reflect capability:')
report_en.append('   • Conservatism: GPT-4o may be more conservative, giving lower scores to')
report_en.append('     uncertain content, unwilling to make complete inferences with insufficient')
report_en.append('     evidence. This conservatism may be an advantage in some scenarios but leads')
report_en.append('     to lower scores in scenarios requiring complete analysis.')
report_en.append('   • Strict Standards: May employ stricter evaluation standards with higher')
report_en.append('     requirements for each reasoning step, leading to lower scores. If true,')
report_en.append('     GPT-4o\'s low scores actually reflect higher quality standards rather than')
report_en.append('     capability deficiencies.')
report_en.append('   • Conciseness: More concise answers may miss steps evaluators consider important,')
report_en.append('     leading to lower scores in dimensions like "Subsumption Chain Alignment".')
report_en.append('     Conciseness is an advantage in some scenarios but a disadvantage when')
report_en.append('     complete reasoning chains are required.')
report_en.append('   • Quality vs Score: Low scores may reflect "more cautious" rather than')
report_en.append('     "poor quality". Review of actual response content is needed to determine')
report_en.append('     whether GPT-4o responses are genuinely lower quality or just more conservative.')
report_en.append('')

report_en.append('VI. PRACTICAL RECOMMENDATIONS')
report_en.append('-' * 80)
report_en.append('')
report_en.append('1. Scenarios Requiring Complete Legal Reasoning Chains')
report_en.append('   Recommendation: DeepSeek')
report_en.append('   Rationale: DeepSeek has clear advantages in constructing systematic, complete')
report_en.append('   legal reasoning, suitable for scenarios requiring full analytical processes,')
report_en.append('   such as legal education, case analysis reports, and legal research. In these')
report_en.append('   scenarios, complete reasoning chains are more important than concise conclusions.')
report_en.append('')
report_en.append('2. Scenarios Requiring Balanced Comprehensive Analysis')
report_en.append('   Recommendation: Gemini 2.5 Flash')
report_en.append('   Rationale: Gemini provides relatively comprehensive but not overly complex')
report_en.append('   analysis, suitable for quickly understanding multiple aspects of cases, such')
report_en.append('   as preliminary case assessment and multi-perspective analysis.')
report_en.append('')
report_en.append('3. Scenarios Requiring Conservative, Strict Evaluation')
report_en.append('   Recommendation: GPT-4o (needs further verification)')
report_en.append('   Rationale: If GPT-4o low scores reflect stricter standards rather than poor')
report_en.append('   quality, it may suit scenarios requiring conservative, cautious analysis,')
report_en.append('   such as risk assessment and compliance checks. However, actual response quality')
report_en.append('   needs further verification.')
report_en.append('')
report_en.append('4. Combined Usage Strategy')
report_en.append('   • Initial Analysis: Use Gemini for quick comprehensive analysis to understand')
report_en.append('     basic case situation')
report_en.append('   • Deep Analysis: Use DeepSeek to construct complete reasoning chains for')
report_en.append('     in-depth legal analysis')
report_en.append('   • Quality Check: Use GPT-4o for conservative verification to identify risks')
report_en.append('     that other models might miss')
report_en.append('')

report_en.append('VII. FUTURE RESEARCH DIRECTIONS')
report_en.append('-' * 80)
report_en.append('')
report_en.append('1. Response Quality Analysis')
report_en.append('   Need in-depth analysis of actual response content from all three models,')
report_en.append('   not just scores, to understand true reasons for gaps. Particularly whether')
report_en.append('   GPT-4o low scores reflect poor quality or stricter evaluation standards.')
report_en.append('   This can be verified through manual evaluation or expert review.')
report_en.append('')
report_en.append('2. Prompt Optimization')
report_en.append('   Try optimizing prompts for different models, especially GPT-4o, to see if')
report_en.append('   scores can be improved through prompt optimization. For example, explicitly')
report_en.append('   require GPT-4o to provide complete reasoning chains, or adjust evaluation')
report_en.append('   standards to better reflect GPT-4o\'s characteristics.')
report_en.append('')
report_en.append('3. Evaluation Standard Consistency')
report_en.append('   Ensure evaluation standards are consistent for all models. If some models')
report_en.append('   score lower due to "more conservative" approach, evaluation standards or')
report_en.append('   methods may need adjustment to better reflect different models\' actual capabilities.')
report_en.append('')
report_en.append('4. Case Diversity')
report_en.append('   Expand test case range to include different types of legal cases (e.g.,')
report_en.append('   contract disputes, tort disputes, criminal cases) to verify conclusion')
report_en.append('   generalizability. Different case types may require different analytical')
report_en.append('   methods and reasoning patterns.')
report_en.append('')

report_en.append('=' * 80)
report_en.append('End of Report')
report_en.append('=' * 80)

# 保存两个版本
timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
cn_file = f'data/模型对比分析报告_中文版_{timestamp}.txt'
en_file = f'data/模型对比分析报告_英文版_{timestamp}.txt'

with open(cn_file, 'w', encoding='utf-8') as f:
    f.write('\n'.join(report_cn))

with open(en_file, 'w', encoding='utf-8') as f:
    f.write('\n'.join(report_en))

cn_length = len('\n'.join(report_cn))
en_length = len('\n'.join(report_en))

print(f'✓ 中文报告已保存: {cn_file}')
print(f'✓ 英文报告已保存: {en_file}')
print(f'\n中文报告长度: {cn_length} 字符')
print(f'英文报告长度: {en_length} 字符')
print(f'\n完整路径:')
print(f'  中文: /Users/chenlong/WorkSpace/huangyidan/{cn_file}')
print(f'  英文: /Users/chenlong/WorkSpace/huangyidan/{en_file}')

